//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Cars { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyCar> CompanyCars { get; set; }
        public DbSet<CompanyCustomerContact> CompanyCustomerContacts { get; set; }
        public DbSet<CompanyCustomerGroup> CompanyCustomerGroups { get; set; }
        public DbSet<CompanyCustomer> CompanyCustomers { get; set; }
        public DbSet<CompanyDriver> CompanyDrivers { get; set; }
        public DbSet<CompanyPart> CompanyParts { get; set; }
        public DbSet<CompanyPassengerGroup> CompanyPassengerGroups { get; set; }
        public DbSet<CompanyPassenger> CompanyPassengers { get; set; }
        public DbSet<CompanyPeriodTime> CompanyPeriodTimes { get; set; }
        public DbSet<CompanyServicePrice> CompanyServicePrices { get; set; }
        public DbSet<CompanySupplierContact> CompanySupplierContacts { get; set; }
        public DbSet<CompanySupplierGroup> CompanySupplierGroups { get; set; }
        public DbSet<CompanySupplier> CompanySuppliers { get; set; }
        public DbSet<CompanyTechnician> CompanyTechnicians { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<DriverLicens> DriverLicenses { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<Period> Periods { get; set; }
        public DbSet<PeriodTime> PeriodTimes { get; set; }
        public DbSet<RideDone> RideDones { get; set; }
        public DbSet<RideDoneCarLocation> RideDoneCarLocations { get; set; }
        public DbSet<RideDoneCar> RideDoneCars { get; set; }
        public DbSet<RideDoneDriverLocation> RideDoneDriverLocations { get; set; }
        public DbSet<RideDoneDriver> RideDoneDrivers { get; set; }
        public DbSet<RideDoneLocation> RideDoneLocations { get; set; }
        public DbSet<RideDonePassengerCompany> RideDonePassengerCompanies { get; set; }
        public DbSet<RideDonePassengerLocation> RideDonePassengerLocations { get; set; }
        public DbSet<RidePlanned> RidePlanneds { get; set; }
        public DbSet<RidePlannedCarLocation> RidePlannedCarLocations { get; set; }
        public DbSet<RidePlannedCar> RidePlannedCars { get; set; }
        public DbSet<RidePlannedDriverLocation> RidePlannedDriverLocations { get; set; }
        public DbSet<RidePlannedDriver> RidePlannedDrivers { get; set; }
        public DbSet<RidePlannedLocation> RidePlannedLocations { get; set; }
        public DbSet<RidePlannedObjectPrice> RidePlannedObjectPrices { get; set; }
        public DbSet<RidePlannedPassengerCompany> RidePlannedPassengerCompanies { get; set; }
        public DbSet<RidePlannedPassengerLocation> RidePlannedPassengerLocations { get; set; }
        public DbSet<RidePlannedTime> RidePlannedTimes { get; set; }
        public DbSet<t_CarBrands> t_CarBrands { get; set; }
        public DbSet<t_CarGroups> t_CarGroups { get; set; }
        public DbSet<t_CarType> t_CarType { get; set; }
        public DbSet<t_CompanyType> t_CompanyType { get; set; }
        public DbSet<t_ContactType> t_ContactType { get; set; }
        public DbSet<t_CustomerGroups> t_CustomerGroups { get; set; }
        public DbSet<t_DriverGroups> t_DriverGroups { get; set; }
        public DbSet<t_DriverType> t_DriverType { get; set; }
        public DbSet<t_EntityType> t_EntityType { get; set; }
        public DbSet<t_Items> t_Items { get; set; }
        public DbSet<t_Languages> t_Languages { get; set; }
        public DbSet<t_LicenseType> t_LicenseType { get; set; }
        public DbSet<t_Locations> t_Locations { get; set; }
        public DbSet<t_NotifyBy> t_NotifyBy { get; set; }
        public DbSet<t_NotifyByTiming> t_NotifyByTiming { get; set; }
        public DbSet<t_NotifyType> t_NotifyType { get; set; }
        public DbSet<t_Parts> t_Parts { get; set; }
        public DbSet<t_PassengerGroups> t_PassengerGroups { get; set; }
        public DbSet<t_RideObjects> t_RideObjects { get; set; }
        public DbSet<t_RideType> t_RideType { get; set; }
        public DbSet<t_Roles> t_Roles { get; set; }
        public DbSet<t_Services> t_Services { get; set; }
        public DbSet<t_SupplierGroups> t_SupplierGroups { get; set; }
        public DbSet<Technician> Technicians { get; set; }
        public DbSet<UserContactType> UserContactTypes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
