//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPeriodTime
    {
        public int CompanyID { get; set; }
        public int PeriodID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public bool IsActiveDay { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual PeriodTime PeriodTime { get; set; }
    }
}
