//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.CompanyCars = new HashSet<CompanyCar>();
            this.CompanyCustomerGroups = new HashSet<CompanyCustomerGroup>();
            this.CompanyDrivers = new HashSet<CompanyDriver>();
            this.CompanyParts = new HashSet<CompanyPart>();
            this.CompanyPassengerGroups = new HashSet<CompanyPassengerGroup>();
            this.CompanyPassengers = new HashSet<CompanyPassenger>();
            this.CompanyPeriodTimes = new HashSet<CompanyPeriodTime>();
            this.CompanyServicePrices = new HashSet<CompanyServicePrice>();
            this.CompanySupplierGroups = new HashSet<CompanySupplierGroup>();
            this.CompanyTechnicians = new HashSet<CompanyTechnician>();
            this.RideDonePassengerCompanies = new HashSet<RideDonePassengerCompany>();
            this.RidePlanneds = new HashSet<RidePlanned>();
            this.RidePlannedPassengerCompanies = new HashSet<RidePlannedPassengerCompany>();
            this.Users = new HashSet<User>();
            this.CompanyCustomers = new HashSet<CompanyCustomer>();
            this.CompanySuppliers = new HashSet<CompanySupplier>();
            this.CompanyCustomers1 = new HashSet<CompanyCustomer>();
            this.CompanySuppliers1 = new HashSet<CompanySupplier>();
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.t_CarGroups = new HashSet<t_CarGroups>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string OrgnuizationNumber { get; set; }
        public byte[] CompanyLogo { get; set; }
        public string WebHeader { get; set; }
        public string WebFooter { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> DistanceUnitID { get; set; }
        public Nullable<long> CompanyTypeID { get; set; }
    
        public virtual ICollection<CompanyCar> CompanyCars { get; set; }
        public virtual ICollection<CompanyCustomerGroup> CompanyCustomerGroups { get; set; }
        public virtual ICollection<CompanyDriver> CompanyDrivers { get; set; }
        public virtual ICollection<CompanyPart> CompanyParts { get; set; }
        public virtual ICollection<CompanyPassengerGroup> CompanyPassengerGroups { get; set; }
        public virtual ICollection<CompanyPassenger> CompanyPassengers { get; set; }
        public virtual ICollection<CompanyPeriodTime> CompanyPeriodTimes { get; set; }
        public virtual ICollection<CompanyServicePrice> CompanyServicePrices { get; set; }
        public virtual ICollection<CompanySupplierGroup> CompanySupplierGroups { get; set; }
        public virtual ICollection<CompanyTechnician> CompanyTechnicians { get; set; }
        public virtual ICollection<RideDonePassengerCompany> RideDonePassengerCompanies { get; set; }
        public virtual ICollection<RidePlanned> RidePlanneds { get; set; }
        public virtual ICollection<RidePlannedPassengerCompany> RidePlannedPassengerCompanies { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<CompanyCustomer> CompanyCustomers { get; set; }
        public virtual ICollection<CompanySupplier> CompanySuppliers { get; set; }
        public virtual ICollection<CompanyCustomer> CompanyCustomers1 { get; set; }
        public virtual ICollection<CompanySupplier> CompanySuppliers1 { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual t_CompanyType t_CompanyType { get; set; }
        public virtual ICollection<t_CarGroups> t_CarGroups { get; set; }
    }
}
