//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDriver
    {
        public CompanyDriver()
        {
            this.RideDoneDrivers = new HashSet<RideDoneDriver>();
            this.RidePlannedDrivers = new HashSet<RidePlannedDriver>();
        }
    
        public int CompanyDriverID { get; set; }
        public int CompanyID { get; set; }
        public string DriverID { get; set; }
        public int DriverGroupID { get; set; }
        public int MainCompanyCarPlatID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual CompanyCar CompanyCar { get; set; }
        public virtual ICollection<RideDoneDriver> RideDoneDrivers { get; set; }
        public virtual ICollection<RidePlannedDriver> RidePlannedDrivers { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual t_DriverGroups t_DriverGroups { get; set; }
    }
}
