//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySupplierContact
    {
        public int CompanySupplierID { get; set; }
        public int ContactID { get; set; }
        public int ContactTypeID { get; set; }
        public string ContactValue { get; set; }
        public string ContactDetails { get; set; }
        public bool IsMain { get; set; }
    
        public virtual CompanySupplier CompanySupplier { get; set; }
        public virtual t_ContactType t_ContactType { get; set; }
    }
}
