//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.CompanyDrivers = new HashSet<CompanyDriver>();
            this.DriverLicenses = new HashSet<DriverLicens>();
            this.t_DriverType = new HashSet<t_DriverType>();
        }
    
        public string DriverID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LicenseDetails { get; set; }
    
        public virtual ICollection<CompanyDriver> CompanyDrivers { get; set; }
        public virtual ICollection<DriverLicens> DriverLicenses { get; set; }
        public virtual ICollection<t_DriverType> t_DriverType { get; set; }
    }
}
