//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicens
    {
        public string DriverID { get; set; }
        public string LicenseTypeID { get; set; }
        public string LicenseTypeDetails { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual t_LicenseType t_LicenseType { get; set; }
    }
}
