//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodTime
    {
        public PeriodTime()
        {
            this.CompanyPeriodTimes = new HashSet<CompanyPeriodTime>();
        }
    
        public int PeriodID { get; set; }
        public System.DateTime Date { get; set; }
        public byte DayInWeek { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CompanyPeriodTime> CompanyPeriodTimes { get; set; }
        public virtual Period Period { get; set; }
    }
}
