//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RidePlanned
    {
        public RidePlanned()
        {
            this.RidePlannedCars = new HashSet<RidePlannedCar>();
            this.RidePlannedDrivers = new HashSet<RidePlannedDriver>();
            this.RidePlannedLocations = new HashSet<RidePlannedLocation>();
            this.RidePlannedObjectPrices = new HashSet<RidePlannedObjectPrice>();
            this.RidePlannedPassengerCompanies = new HashSet<RidePlannedPassengerCompany>();
            this.RidePlannedPassengerLocations = new HashSet<RidePlannedPassengerLocation>();
            this.RidePlannedTimes = new HashSet<RidePlannedTime>();
        }
    
        public int RidePlannedID { get; set; }
        public int OriginCompanyID { get; set; }
        public string RideName { get; set; }
        public int OriginLocationID { get; set; }
        public int DestinationLocationID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string DriverPreferences { get; set; }
        public bool IsTravelRepeat { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> RideTypeID { get; set; }
        public Nullable<int> CarTypeID { get; set; }
        public long EstimatedTravelMinutes { get; set; }
        public long EstimatedTravelDistance { get; set; }
        public string Escort { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Period Period { get; set; }
        public virtual ICollection<RidePlannedCar> RidePlannedCars { get; set; }
        public virtual ICollection<RidePlannedDriver> RidePlannedDrivers { get; set; }
        public virtual ICollection<RidePlannedLocation> RidePlannedLocations { get; set; }
        public virtual ICollection<RidePlannedObjectPrice> RidePlannedObjectPrices { get; set; }
        public virtual ICollection<RidePlannedPassengerCompany> RidePlannedPassengerCompanies { get; set; }
        public virtual ICollection<RidePlannedPassengerLocation> RidePlannedPassengerLocations { get; set; }
        public virtual ICollection<RidePlannedTime> RidePlannedTimes { get; set; }
        public virtual t_CarType t_CarType { get; set; }
        public virtual t_Locations t_Locations { get; set; }
        public virtual t_Locations t_Locations1 { get; set; }
        public virtual t_RideType t_RideType { get; set; }
    }
}
