//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RidePlannedDriver
    {
        public RidePlannedDriver()
        {
            this.RidePlannedDriverLocations = new HashSet<RidePlannedDriverLocation>();
        }
    
        public int RidePlannedID { get; set; }
        public int CompanyDriverID { get; set; }
        public double Percentage { get; set; }
    
        public virtual CompanyDriver CompanyDriver { get; set; }
        public virtual RidePlanned RidePlanned { get; set; }
        public virtual ICollection<RidePlannedDriverLocation> RidePlannedDriverLocations { get; set; }
    }
}
