//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDonePassengerLocation
    {
        public RideDonePassengerLocation()
        {
            this.RidePlannedPassengerLocations = new HashSet<RidePlannedPassengerLocation>();
        }
    
        public int RideDonePassengerLocationsID { get; set; }
        public int RideDoneID { get; set; }
        public int CompanyPassengerID { get; set; }
        public int RideDoneLocationsID { get; set; }
    
        public virtual CompanyPassenger CompanyPassenger { get; set; }
        public virtual RideDone RideDone { get; set; }
        public virtual RideDoneLocation RideDoneLocation { get; set; }
        public virtual ICollection<RidePlannedPassengerLocation> RidePlannedPassengerLocations { get; set; }
    }
}
