//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDone
    {
        public RideDone()
        {
            this.RideDoneCars = new HashSet<RideDoneCar>();
            this.RideDoneDrivers = new HashSet<RideDoneDriver>();
            this.RideDoneLocations = new HashSet<RideDoneLocation>();
            this.RideDonePassengerCompanies = new HashSet<RideDonePassengerCompany>();
            this.RideDonePassengerLocations = new HashSet<RideDonePassengerLocation>();
            this.RidePlannedTimes = new HashSet<RidePlannedTime>();
        }
    
        public int RideDoneID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
    
        public virtual ICollection<RideDoneCar> RideDoneCars { get; set; }
        public virtual ICollection<RideDoneDriver> RideDoneDrivers { get; set; }
        public virtual ICollection<RideDoneLocation> RideDoneLocations { get; set; }
        public virtual ICollection<RideDonePassengerCompany> RideDonePassengerCompanies { get; set; }
        public virtual ICollection<RideDonePassengerLocation> RideDonePassengerLocations { get; set; }
        public virtual ICollection<RidePlannedTime> RidePlannedTimes { get; set; }
    }
}
