//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDoneDriverLocation
    {
        public RideDoneDriverLocation()
        {
            this.RidePlannedDriverLocations = new HashSet<RidePlannedDriverLocation>();
        }
    
        public int RideDoneDriverLocationsID { get; set; }
        public int RideDoneID { get; set; }
        public int CompanyDriverID { get; set; }
        public int RideDoneLocationsID { get; set; }
    
        public virtual ICollection<RidePlannedDriverLocation> RidePlannedDriverLocations { get; set; }
        public virtual RideDoneDriver RideDoneDriver { get; set; }
        public virtual RideDoneLocation RideDoneLocation { get; set; }
    }
}
