//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDonePassengerCompany
    {
        public RideDonePassengerCompany()
        {
            this.RidePlannedPassengerCompanies = new HashSet<RidePlannedPassengerCompany>();
        }
    
        public int RideDonePassengerCompanyID { get; set; }
        public int RideDoneID { get; set; }
        public int CompanyID { get; set; }
        public double Percentage { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual RideDone RideDone { get; set; }
        public virtual ICollection<RidePlannedPassengerCompany> RidePlannedPassengerCompanies { get; set; }
    }
}
