//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RidePlannedCar
    {
        public RidePlannedCar()
        {
            this.RidePlannedCarLocations = new HashSet<RidePlannedCarLocation>();
        }
    
        public int RidePlannedID { get; set; }
        public int CompanyCarPlatID { get; set; }
        public double Percentage { get; set; }
    
        public virtual CompanyCar CompanyCar { get; set; }
        public virtual RidePlanned RidePlanned { get; set; }
        public virtual ICollection<RidePlannedCarLocation> RidePlannedCarLocations { get; set; }
    }
}
