//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RidePlannedLocation
    {
        public RidePlannedLocation()
        {
            this.RidePlannedCarLocations = new HashSet<RidePlannedCarLocation>();
            this.RidePlannedDriverLocations = new HashSet<RidePlannedDriverLocation>();
            this.RidePlannedPassengerLocations = new HashSet<RidePlannedPassengerLocation>();
        }
    
        public int RidePlannedID { get; set; }
        public int RidePlannedTimesID { get; set; }
        public int RidePlannedLocationsID { get; set; }
        public int FromLocationID { get; set; }
        public int ToLocationID { get; set; }
        public int EstimatedRideMinutes { get; set; }
        public int EstimatedRideCost { get; set; }
        public System.TimeSpan OnTime { get; set; }
        public int Quantity { get; set; }
        public int ServiceID { get; set; }
        public bool IsActive { get; set; }
        public int RideDoneLocationsID { get; set; }
    
        public virtual RideDoneLocation RideDoneLocation { get; set; }
        public virtual RidePlanned RidePlanned { get; set; }
        public virtual ICollection<RidePlannedCarLocation> RidePlannedCarLocations { get; set; }
        public virtual ICollection<RidePlannedDriverLocation> RidePlannedDriverLocations { get; set; }
        public virtual ICollection<RidePlannedPassengerLocation> RidePlannedPassengerLocations { get; set; }
        public virtual RidePlannedTime RidePlannedTime { get; set; }
        public virtual t_Locations t_Locations { get; set; }
        public virtual t_Locations t_Locations1 { get; set; }
        public virtual t_Services t_Services { get; set; }
    }
}
