//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RideDoneLocation
    {
        public RideDoneLocation()
        {
            this.RideDoneCarLocations = new HashSet<RideDoneCarLocation>();
            this.RideDoneDriverLocations = new HashSet<RideDoneDriverLocation>();
            this.RideDonePassengerLocations = new HashSet<RideDonePassengerLocation>();
            this.RidePlannedLocations = new HashSet<RidePlannedLocation>();
        }
    
        public int RideDoneID { get; set; }
        public int RideDoneLocationsID { get; set; }
        public int FromLocationID { get; set; }
        public int ToLocationID { get; set; }
        public long RideMinutes { get; set; }
        public System.TimeSpan OnTime { get; set; }
        public int Quantity { get; set; }
        public int ServiceID { get; set; }
    
        public virtual RideDone RideDone { get; set; }
        public virtual ICollection<RideDoneCarLocation> RideDoneCarLocations { get; set; }
        public virtual ICollection<RideDoneDriverLocation> RideDoneDriverLocations { get; set; }
        public virtual ICollection<RideDonePassengerLocation> RideDonePassengerLocations { get; set; }
        public virtual ICollection<RidePlannedLocation> RidePlannedLocations { get; set; }
        public virtual t_Locations t_Locations { get; set; }
        public virtual t_Locations t_Locations1 { get; set; }
        public virtual t_Services t_Services { get; set; }
    }
}
