//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CarType
    {
        public t_CarType()
        {
            this.RidePlanneds = new HashSet<RidePlanned>();
            this.t_CarBrands = new HashSet<t_CarBrands>();
            this.t_LicenseType = new HashSet<t_LicenseType>();
        }
    
        public int CarTypeID { get; set; }
        public string Name { get; set; }
        public int PassengersCapacity { get; set; }
    
        public virtual ICollection<RidePlanned> RidePlanneds { get; set; }
        public virtual ICollection<t_CarBrands> t_CarBrands { get; set; }
        public virtual ICollection<t_LicenseType> t_LicenseType { get; set; }
    }
}
