//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CarBrands
    {
        public t_CarBrands()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int CarBrandID { get; set; }
        public string CarManufacturer { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public int CarTypeID { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual t_CarType t_CarType { get; set; }
    }
}
