//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ContactType
    {
        public t_ContactType()
        {
            this.CompanyCustomerContacts = new HashSet<CompanyCustomerContact>();
            this.CompanySupplierContacts = new HashSet<CompanySupplierContact>();
            this.UserContactTypes = new HashSet<UserContactType>();
        }
    
        public int ContactTypeID { get; set; }
        public string ContactTypeCode { get; set; }
        public string ContactTypeDesc { get; set; }
    
        public virtual ICollection<CompanyCustomerContact> CompanyCustomerContacts { get; set; }
        public virtual ICollection<CompanySupplierContact> CompanySupplierContacts { get; set; }
        public virtual ICollection<UserContactType> UserContactTypes { get; set; }
    }
}
