//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CompanyType
    {
        public t_CompanyType()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public long CompanyTypeID { get; set; }
        public string CompanyTypeName { get; set; }
        public Nullable<int> EntityTypeIDs { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
    }
}
