//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CustomerGroups
    {
        public t_CustomerGroups()
        {
            this.CompanyCustomerGroups = new HashSet<CompanyCustomerGroup>();
        }
    
        public int CustomerGroupID { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<CompanyCustomerGroup> CompanyCustomerGroups { get; set; }
    }
}
