//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_LicenseType
    {
        public t_LicenseType()
        {
            this.DriverLicenses = new HashSet<DriverLicens>();
            this.t_CarType = new HashSet<t_CarType>();
        }
    
        public string LincenseTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DriverLicens> DriverLicenses { get; set; }
        public virtual ICollection<t_CarType> t_CarType { get; set; }
    }
}
