//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_NotifyBy
    {
        public t_NotifyBy()
        {
            this.CompanyUsers = new HashSet<CompanyUser>();
        }
    
        public int NotifyByID { get; set; }
        public string NotifyByDesc { get; set; }
    
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
    }
}
