//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Parts
    {
        public t_Parts()
        {
            this.CompanyParts = new HashSet<CompanyPart>();
        }
    
        public string PartID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CompanyPart> CompanyParts { get; set; }
    }
}
