//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RideType
    {
        public t_RideType()
        {
            this.RidePlanneds = new HashSet<RidePlanned>();
        }
    
        public int RideTypeID { get; set; }
        public string RideCode { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<RidePlanned> RidePlanneds { get; set; }
    }
}
