//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_RideObjects
    {
        public t_RideObjects()
        {
            this.RidePlannedObjectPrices = new HashSet<RidePlannedObjectPrice>();
        }
    
        public int RideObjectID { get; set; }
        public string RideObjectDesc { get; set; }
    
        public virtual ICollection<RidePlannedObjectPrice> RidePlannedObjectPrices { get; set; }
    }
}
