//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Roles
    {
        public t_Roles()
        {
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.t_Items = new HashSet<t_Items>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual ICollection<t_Items> t_Items { get; set; }
    }
}
