//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Services
    {
        public t_Services()
        {
            this.CompanyServicePrices = new HashSet<CompanyServicePrice>();
            this.RideDoneLocations = new HashSet<RideDoneLocation>();
            this.RidePlannedLocations = new HashSet<RidePlannedLocation>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceDesc { get; set; }
    
        public virtual ICollection<CompanyServicePrice> CompanyServicePrices { get; set; }
        public virtual ICollection<RideDoneLocation> RideDoneLocations { get; set; }
        public virtual ICollection<RidePlannedLocation> RidePlannedLocations { get; set; }
    }
}
