//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CompanyCustomerContacts = new HashSet<CompanyCustomerContact>();
            this.CompanyUsers = new HashSet<CompanyUser>();
            this.UserContactTypes = new HashSet<UserContactType>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public int LanguageID { get; set; }
        public int MainCompanyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompanyCustomerContact> CompanyCustomerContacts { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
        public virtual t_Languages t_Languages { get; set; }
        public virtual ICollection<UserContactType> UserContactTypes { get; set; }
    }
}
